### ISSUE TITLE
Issue when ModVar = 1. I suppose it is a syntax error.

### ISSUE THREAD

**Issue by Markkolas** [tmd224/pyitm#1]
Hey! First of all, nice work on porting the ITM to Python, made my life much easier!

Second, I am afraid there is a problem with the port, and it manifest when ModVar = 1. With the values you use in https://pyitm.readthedocs.io/en/latest/user-guide.html and ModVar = 1 the next error appears:
`Traceback (most recent call last):
  File "/home/mark/test.py", line 22, in <module>
    dbloss = ITMAreadBLoss(ModVar, deltaH, tht_m, rht_m, dist_km,
  File "/home/mark/.local/lib/python3.9/site-packages/pyitm/itm.py", line 1011, in ITMAreadBLoss
    dbloss, _ = area(ModVar, deltaH, tht_m, rht_m, dist_km, TSiteCriteria,
  File "/home/mark/.local/lib/python3.9/site-packages/pyitm/itm.py", line 954, in area
    xlb = fs + avar(zt, zl, zc, prop, propv)
  File "/home/mark/.local/lib/python3.9/site-packages/pyitm/itm.py", line 791, in avar
    propv.sgc = math.sqrt(avar.sg1 * avar.sgl + vs)
AttributeError: 'function' object has no attribute 'sg1'
`
I took a quick look at your code and noticed the incredible fact that here:
https://github.com/tmd224/pyitm/blob/2930765eb6cb5c9d0c02b10c64f62ec9f985ce2b/pyitm/itm.py#L746-L751

the sg1 variable is not declared inside the else statement. Changing avar.sgl to avar.sg1 fixed the thing, it was just a dumb syntax error.
I did not want to do an entire fork of the thing just to send a pull request so I'll just leave this issue here. Hope you can fix it soon!

**Comment by tmd224** [comment]
Thanks for submitting a bug report.  I've fixed the issue and will upload a new version soon.
